export const ContactPermissions = {
  CREATE: 'CREATE_CONTACT',
  READ: 'READ_CONTACT',
  UPDATE: 'UPDATE_CONTACT',
  ACTIVATE: 'ACTIVATE_CONTACT',
  DEACTIVATE: 'DEACTIVATE_CONTACT',
  MANAGE_ROLES: 'MANAGE_CONTACT_ROLES',
  LIST: 'LIST_CONTACTS',
  VIEW_ROLE_TYPES: 'VIEW_CONTACT_ROLE_TYPES',
  ASSIGN: 'ASSIGN_CONTACT',
} as const;
